# Generated by Django 6.0.2 on 2026-02-21 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantBranding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('primary_color', models.CharField(blank=True, help_text='Hex color code (e.g. #FFFFFF)', max_length=7)),
                ('secondary_color', models.CharField(blank=True, help_text='Hex color code (e.g. #000000)', max_length=7)),
                ('theme_tokens', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantHostAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_aliases', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campus_only', models.BooleanField(default=True)),
                ('invite_only', models.BooleanField(default=False)),
                ('enforce_email_domains', models.BooleanField(default=False)),
                ('enforce_ip_allowlist', models.BooleanField(default=False)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('lockout_minutes', models.IntegerField(default=15)),
                ('otp_ttl_seconds', models.IntegerField(default=300)),
                ('access_token_ttl_seconds', models.IntegerField(default=900)),
                ('refresh_token_ttl_seconds', models.IntegerField(default=604800)),
                ('require_2fa_email_otp', models.BooleanField(default=False)),
                ('allow_remember_device', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantEmailDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_domains', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'domain')},
            },
        ),
    ]
