# Generated by Django 6.0.2 on 2026-02-22 00:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('S3', 'S3'), ('SPACES', 'Spaces'), ('MINIO', 'MinIO')], default='S3', max_length=50)),
                ('bucket', models.CharField(max_length=255)),
                ('object_key', models.CharField(max_length=1024)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('checksum', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='repository.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_theses', to='users.tenantmembership')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theses', to='repository.department')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theses', to='repository.program')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theses', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThesisAdviser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adviser_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advised_theses', to='users.tenantmembership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisers', to='repository.thesis')),
            ],
        ),
        migrations.CreateModel(
            name='ThesisAuthor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='repository.thesis')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_theses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ThesisFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('MAIN_PDF', 'Main PDF'), ('ATTACHMENT', 'Attachment')], default='MAIN_PDF', max_length=50)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.fileobject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='repository.thesis')),
                ('uploaded_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tenantmembership')),
            ],
        ),
        migrations.CreateModel(
            name='ThesisReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes Requested')], default='PENDING', max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.tenantmembership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='repository.thesis')),
            ],
        ),
        migrations.CreateModel(
            name='ThesisStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tenantmembership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='repository.thesis')),
            ],
        ),
        migrations.CreateModel(
            name='ThesisKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_keywords', to='repository.keyword')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_keywords', to='repository.thesis')),
            ],
            options={
                'unique_together': {('thesis', 'keyword')},
            },
        ),
    ]
