# Generated by Django 6.0.2 on 2026-02-22 02:27

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
        ('tenants', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='thesis',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='repository__search__a16408_gin'),
        ),
    ]
