# Generated by Django 6.0.2 on 2026-03-21 03:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_thesis_search_vector_and_more'),
        ('tenants', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisMetadataVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version_number', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='thesis',
            name='campus_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='thesis',
            name='college_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='thesis',
            name='defense_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thesis',
            name='embargo_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thesis',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='thesis',
            name='methodology',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='thesis',
            name='panel_members',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='thesis',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='thesis',
            name='research_category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='thesis',
            name='rights_license',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='thesis',
            name='thesis_type',
            field=models.CharField(choices=[('THESIS', 'Thesis'), ('CAPSTONE', 'Capstone'), ('DISSERTATION', 'Dissertation')], default='THESIS', max_length=50),
        ),
        migrations.AddField(
            model_name='thesis',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('CAMPUS_ONLY', 'Campus Only'), ('PUBLIC', 'Public'), ('EMBARGOED', 'Embargoed')], default='PRIVATE', max_length=50),
        ),
        migrations.AddField(
            model_name='thesisfile',
            name='access_level',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('VIEW_ONLY', 'View Only'), ('DOWNLOADABLE', 'Downloadable')], default='DOWNLOADABLE', max_length=50),
        ),
        migrations.AddField(
            model_name='thesisfile',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='thesisfile',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In Review'), ('CHANGES_REQUESTED', 'Changes Requested'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=50),
        ),
        migrations.AddIndex(
            model_name='thesis',
            index=models.Index(fields=['tenant', 'public_slug'], name='repository__tenant__0f6e80_idx'),
        ),
        migrations.AddIndex(
            model_name='thesis',
            index=models.Index(fields=['tenant', 'visibility', 'status'], name='repository__tenant__6f6fdf_idx'),
        ),
        migrations.AddConstraint(
            model_name='thesis',
            constraint=models.UniqueConstraint(condition=models.Q(('public_slug', ''), _negated=True), fields=('tenant', 'public_slug'), name='uniq_repository_thesis_public_slug_per_tenant'),
        ),
        migrations.AddField(
            model_name='thesismetadataversion',
            name='created_by_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_versions', to='users.tenantmembership'),
        ),
        migrations.AddField(
            model_name='thesismetadataversion',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_metadata_versions', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='thesismetadataversion',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_versions', to='repository.thesis'),
        ),
        migrations.AlterUniqueTogether(
            name='thesismetadataversion',
            unique_together={('thesis', 'version_number')},
        ),
    ]
